#!/bin/bash
mkdir -p "$HOME/logarchives/"
currentDate="$(date +%Y-%m-%d)"
if [[ -a "$HOME/logarchives/$currentDate" ]]; then
    mc-log "[mc-log-migrate] ${currentDate} already exists"
    numb='1'
    while [[ -a "$HOME/logarchives/${currentdate}-${numb}.log" ]]; do
        numb1="$(($numb1 + 1))"
    done
    mc-log "[mc-log-migrate] Migrating log to ${currentDate}-${numb}.log"
    cp "$HOME/server/server.log" "$HOME/logarchives/${currentDate}-${numb}.log"
else
    mc-log "[mc-log-migrate] Migrating log to ${currentDate}.log"
    cp "$HOME/server/server.log" "$HOME/logarchives/${currentDate}.log"
fi
echo > "$HOME/server/server.log"
