#!/bin/bash
if [[ `mc-script-enabled` ]]; then
    if [[ "`mc-server-running`" ]]; then
        mc-log "[mc-server-script] Server running"
    else
        mc-log "[mc-server-script] Restarting server"
        mc-kill-server
        mc-start-server
    fi
else
    mc-log "[mc-server-script] Script disabled"
fi
