#!/bin/bash
mc-log "[mc-backup] Starting"
log="$HOME/logs/`date +%Y-%m-%d`.log"
touch "$log"
backuplocation="file://$HOME/backups/mainserver"
duplicity --no-encryption \
    --log-file="$log" \
    --name "local-mainserver-backup" \
    --full-if-older-than 1W \
    "$HOME/server" "$backuplocation" >> "$log"
mc-log "[mc-backup] Done"
