#!/bin/bash
if [[ -a "$HOME/.script-disabled" ]]; then
    mc-log "[mc-disable-script] Script already disabled"
else
    mc-log "[mc-disable-script] Disabling script"
fi
touch "$HOME/.script-disabled"
