#!/bin/bash
currentversion="`mc-current-version`"
latestversion="`mc-latest-version`"
if [[ "$currentversion" != "$latestversion" ]]; then
    mc-log "[mc-download-latest] Server outdated"
    mc-log "[mc-download-latest] Downloading..."
    wget "http://ci.md-5.net/job/Spigot/lastSuccessfulBuild/artifact/Spigot-Server/target/spigot.jar" -O "$HOME/server/spigot.jar.new"
    ok="`java -jar $HOME/server/spigot.jar.new --version`"
    times=0
    until [[ "$ok" || "$times" -gt "5" ]]; do
        rm -f "$HOME/server/spigot.jar.new"
        mc-log "[mc-download-latest] Downloaded jar corrupt"
        mc-log "[mc-download-latest] Downloading..."
        wget "http://ci.md-5.net/job/Spigot/lastSuccessfulBuild/artifact/Spigot-Server/target/spigot.jar" -O "$HOME/server/spigot.jar.new"
        ok="`java -jar $HOME/server/spigot.jar.new --version`"
        times="`expr $times + 1`"
    done
    if [[ "$ok" ]]; then
        mc-log "[mc-download-latest] Download successful"
        mc-log "[mc-download-latest] Deploying"
        if [[ -a "$HOME/server/spigot.jar" ]]; then
            rm -f "$HOME/server/spigot.jar"
        fi
        mv "$HOME/server/spigot.jar.new" "$HOME/server/spigot.jar"
    else
        mc-log "[mc-download-latest] Downloaded 5 corrupt jars"
        mc-log "[mc-download-latest] Giving up"
        rm -f "$HOME/server/spigot.jar.new"
    fi
else
    mc-log "[mc-download-latest] Server up to date"
fi
