#!/bin/bash
if [[ ! -d "$HOME/logs" ]]; then
    if [[ -a "$HOME/logs" ]]; then
        mv "$HOME/logs" "$HOME/logs_bak"
    fi
    mkdir "$HOME/logs"
fi
log="$HOME/logs/`date +%Y-%m-%d`.log"
touch "$log"
echo "$log"
# To disable logging, comment out the above and uncomment the below
#echo "/dev/null"
