#!/bin/bash
mc-log "[mc-restart-warning-long] Starting"
if [[ "`mc-server-running`" ]]; then
    mc-tell-server 'say Warning! Restarting in 5 minutes!'
    sleep 60
    if [[ "`mc-server-running`" ]]; then
        mc-tell-server 'say Warning! Restarting in 4 minutes!'
        sleep 60
        if [[ "`mc-server-running`" ]]; then
            mc-tell-server 'say Warning! Restarting in 3 minutes!'
            sleep 60
            if [[ "`mc-server-running`" ]]; then
                mc-tell-server 'say Warning! Restarting in 2 minutes!'
                sleep 60
                if [[ "`mc-server-running`" ]]; then
                    mc-tell-server 'say Warning! Restarting in 1 minute!'
                    sleep 60
                fi
            fi
        fi
    fi
fi
mc-log "[mc-restart-warning-long] Done"
