#!/bin/bash
if [[ "`mc-server-running`" ]]; then
    mc-log "[mc-stop-server] Stopping server"
    mc-tell-server "kickall Server is restarting"
    mc-tell-server "stop"
    timeout="`expr 120 + $(date '+%s')`"
    while [[ "`mc-server-running`" ]]; do
        if [[ "`date '+%s'`" -gt "$timeout" ]]; then
            mc-kill-server
        fi
        sleep 1s
    done
else
    mc-log "[mc-stop-server] Server not running"
fi
