#!/bin/bash
jarfile="$HOME/jars/spigot.jar"
xmx="`cat $HOME/.server-xmx`"
xms="`cat $HOME/.server-xms`"
if [[ ! "$xmx" ]]; then
    xmx="1g"
fi
if [[ ! "$xms" ]]; then
    xms="$xmx"
fi
mc-log "[mc-start] Running; jar=$jarfile; xmx=$xmx; xms=$xms"

cd "$HOME/server/"
java -Xms"$xms" -Xmx"$xmx" -Xincgc -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=64m -jar "$jarfile" --log-strip-color
mc-log "[mc-start] Done"
