#!/bin/bash
bc-log "[bc-backup] Starting"
log="`bc-get-log`"
backuplocation="file:///mnt/backup/`whoami`"
duplicity --no-encryption \
    --log-file="$log" \
    --name "`whoami`" \
    --achive-dir "/mnt/backup/archives"
    --full-if-older-than 1W \
    "$HOME" "$backuplocation" >> "$log"
bc-log "[bc-backup] Done"
