#!/bin/bash
if [[ -a "$HOME/.script-disabled" ]]; then
    bc-log "[bc-disable-script] Script already disabled"
else
    bc-log "[bc-disable-script] Disabling script"
    touch "$HOME/.script-disabled"
fi
